// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Wallet.Infrastructure;

#nullable disable

namespace Wallet.Infrastructure.Migrations
{
    [DbContext(typeof(WalletDBContext))]
    [Migration("20250407081606_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Wallet.Domain.Models.AccountOfPerson.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.Family", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HeadMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("HeadMemberId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid");

                    b.HasKey("Id")
                        .HasName("OwnerId");

                    b.HasIndex("WalletId");

                    b.ToTable("FamilyMembers");

                    b.HasDiscriminator().HasValue("FamilyMember");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<Guid>("FamilyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId");

                    b.ToTable("Wallets");

                    b.HasDiscriminator().HasValue("Wallet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.HeadMember", b =>
                {
                    b.HasBaseType("Wallet.Domain.Models.WalletOfFamily.FamilyMember");

                    b.HasDiscriminator().HasValue("HeadMember");
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.SubWallet", b =>
                {
                    b.HasBaseType("Wallet.Domain.Models.WalletOfFamily.Wallet");

                    b.Property<Guid>("ParentWalletId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("WalletId")
                        .HasColumnType("uuid");

                    b.HasIndex("ParentWalletId");

                    b.HasIndex("WalletId");

                    b.HasDiscriminator().HasValue("SubWallet");
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.Family", b =>
                {
                    b.HasOne("Wallet.Domain.Models.WalletOfFamily.HeadMember", "HeadMember")
                        .WithMany()
                        .HasForeignKey("HeadMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HeadMember");
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.FamilyMember", b =>
                {
                    b.HasOne("Wallet.Domain.Models.WalletOfFamily.SubWallet", null)
                        .WithMany("FamilyMembers")
                        .HasForeignKey("WalletId");
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.Wallet", b =>
                {
                    b.HasOne("Wallet.Domain.Models.WalletOfFamily.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.SubWallet", b =>
                {
                    b.HasOne("Wallet.Domain.Models.WalletOfFamily.Wallet", "ParentWallet")
                        .WithMany()
                        .HasForeignKey("ParentWalletId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Wallet.Domain.Models.WalletOfFamily.Wallet", null)
                        .WithMany("SubWallets")
                        .HasForeignKey("WalletId");

                    b.Navigation("ParentWallet");
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.Wallet", b =>
                {
                    b.Navigation("SubWallets");
                });

            modelBuilder.Entity("Wallet.Domain.Models.WalletOfFamily.SubWallet", b =>
                {
                    b.Navigation("FamilyMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
